---
page-layout: article
title: "CV"
---
  

Professional Positions
======
* 2025-present: **Fisheries Biologist**, [Saltwater Inc.](https://www.saltwaterinc.com/) in support of NOAA Fisheries, NEFSC
* 2024 - 2025 **Fisheries Biologist**, [NOAA Fisheries](https://www.fisheries.noaa.gov/),Narragansett,RI


Education
======
  
* Ph.D., Ecology, Evolution and Marine Biology, [Northeastern University,Boston, MA](https://cos.northeastern.edu/marinescience/), 2019
* B.S., Biology, [Eastern Connecticut State University](https://www.easternct.edu/index.html), 2012


Publications
======
* Stoltz, L., Maynard, G., Morin, M., **Salois, S.**, 2025. Production of an in-situ bottom water 
   	temperature product for the northeast US continental shelf using oceanographic data 
    collected by fishing vessels. NOAA Technical Memorandum NMFS-PEMAD. 

* Silver, A., Oliver, H., Gawarkiewicz, G., Fratantoni, P. and **Salois, S.L.**, 2024. Forecasting 
    and seasonal variability of the foot of the Shelfbreak Front in the Northern Middle Atlantic
    Bight. ICES Journal of Marine Science, p.fsae156. 

* **Salois, S.L.** , Owen, S., Molina, A., Jones A.W., Hyde, K.J.W. 2024. Golden Tilefish Ecosystem      and Socioeconomic Profile. Working paper for the 2024 Golden Tilefish Research Track 
      Assessment. 

* Jones, A. W., **Salois, S.L. 2024**. Exploring a CPUE index from trawl gear using high-resolution        catch data.Working paper for the 2024 Golden Tilefish Research Track Assessment. 
* Mercer, A.J.M., Moser, J., Swiader T.J.R., **Salois S.L.**, 2023 Design, Implementation, and 
     Results of a Cooperative Research Shortfin Squid (Illex illecebrousus) Electronic Size 
     Monitoring Pilot Project. NOAA Technical Memorandum NMFS-FMRD. 

* Mercer, A.J.M., Manderson, J.P., Lowman, B., **Salois S.L.**, Hyde, K.J.W., Pessutti J., Jones  
    A.W., Ruhle R., Bright, B., Sawyer T., Lapp, M., Kaelin, J., Almeida, K., DiDomenico, G. 2023. 
    Bringing in the experts: Application of industry knowledge to advance catch rate 
    standardization for northern shortfin squid (Illex illecebrosus). Frontiers in Marine 
    Science.10:1144108.
* **Salois, S.L.**, Hyde, K.J.W., Silver, A.M., Gangopadhyay, A., Gawarkiewicz, G., Mercer, A.J.M.,
    Lowman, B., Manderson, J.P., Gaichas, S.K., Hocking, D.J., Galuardi, B., Jones, A.W., Kaelin,  
    J., DiDomenico, G., Almeida, K., Bright, B., Lapp, M. 2023. Shelf break exchange processes 
    influence the availability of the Northern Shortfin Squid, Illex illecebrosus, in the 
    Northwest Atlantic. Fisheries Oceanography.  

Presentations
======
* Salois, S.L. (2025). Commercial Squid Fisheries in the Northeast Continental Shelf Ecosystem.   Invited talk: Mission is the OCEAN (MOCEAN), Tufts University,  Boston, MA.

* Salois, S.L. and Munley, Mary Kate (2024). Using Collaborative research to understand regional oceanographic influences on Northern shortfin squid distribution. NOAA Climate seminar. 

* Salois, S.L., Hyde KJW, Mercer A,  Jones A, Nitschke P, Lucey S (2024). Novel use of Ecosystem Information to Support Management of Data Limited Species. Oral presentation: World Fisheries Conference, Seattle, WA.

* Salois, S.L and Hyde KJW. (2023). Quantifying frontal dynamics at ecologically and economically relevant spatial and temporal scales. Oral presentation: ICES Annual Science Conference, Bilbao, Spain.

* Salois, S.L and Hyde KJW. (2023).Using a collaborative framework to identify oceanographic indicators of Illex illecebrosus: Origination of the Squid Squad. Oral presentation: Mid-Atlantic Cooperative Research Summit, Newport News, VA. 

* Salois, S.L. and Hyde KJW. (2022). Deriving metrics from remote sensing and modeled data to relate oceanographic conditions to availability for the Northern shortfin squid fishery. Oral presentation: ICES Annual Science Conference, Dublin, Ireland. 